class House:
  def display(self):
        print(f"Ściany: {self.wall}")
        print(f"Drzwi: {self.door}")
        print(f"Okna: {self.window}")
        print(f"Podłoga: {self.floor}")
        print(f"Ogród: {self.garden}")
        print(f"Garaż: {self.garage}")
        print(f"Basen: {self.swimming_pool}")
